### ISSUE TITLE
Cell selection error

### ISSUE THREAD

**Issue by jamestrew** [trewjames/honorable-sudoku#2]
Unable to select cells when you start a game for a second time.

**Reproducible steps**: go back to the startup or options page, and return to the game.
**Runtime error message**:
```
Traceback (most recent call last):
  File "\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "\honorable-sudoku\Pages\game.py", line 213, in select_cell
    if depth == self.__grid.w_depth:
  File "\honorable-sudoku\Pages\game.py", line 41, in w_depth
    return leaf.winfo_parent().count('!')  # determining the depth
  File "\Python\Python38-32\lib\tkinter\__init__.py", line 1114, in winfo_parent
    return self.tk.call('winfo', 'parent', self._w)
_tkinter.TclError: bad window path name ".!frame.!frame.!frame6.!frame.!frame.!frame.!label"
```

**Comment by mineugene** [comment]
Commit f1086c0 fixes this issue.

**Comment by mineugene** [comment]
Edit: removed private path from error message shown in prior edits.
